name: Test Build
on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    name: Build Site
    runs-on: alpine:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: true  # Falls du Git-Submodules (z. B. für Themes) nutzt
        path: .           # Ggf. ändern, falls du ein Verzeichnis mit dem Checkout anlegen willst

    - name: Install Hugo
      run: |
        apk add --no-cache --update-cache --virtual .build-deps $ Hugo extended-binaries
        apk add --no-cache --update-cache git
        # Dieser Schritt kann für deine Hugo-Version angepasst werden (aktuell: hugo_0.94.0-r0.apk)

    - name: Build
      run: hugo --minify --baseURL "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
      working-directory: .     # Falls der Checkout in ein Unterverzeichnis klonen wollte

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        # Optional: Bei Fehlern im vorherigen Schritt während des Deployments löschen
        # keep_files: false  # Löscht die veralteten Dateien
        # force_clean: true   # Für jeden Schritt löscht es wieder
